name: TestServerUtil
version: ${project.version}
main: net.kunmc.lab.testserverutil.TestServerUtil
api-version: 1.16
commands:
  tsu:
    usage: |-
      /tsu opBlacklist <add|remove> <name>
    default: op