name: DevServerUtil
version: ${project.version}
main: net.kunmc.lab.devserverutil.DevServerUtil
api-version: 1.16
commands:
  dsu:
    usage: |-
      /dsu opBlacklist <add|remove> <name>
      /dsu serverProperties <configItem> <value>
      /dsu plugin <enable|disable> <pluginName>
      /dsu flyspeed <player> <speed>
    default: op